version: "3.7"
services:
  postgres:
    image: postgres:13.5-alpine
    container_name: 2022-exam-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  db-data:
    driver: local
